name: ArcherDiscordLink
main: me.staylords.sync.SyncPlugin
version: ${project.version}-${git.commit.id.abbrev}/${git.branch}
description: ${git.remote.origin.url}
author: ${git.build.user.name}
softdepend:
  - DiscordSRV
depend:
  - DeluxeCoinflip
  - Tokens
  - EconomyAPI
  - TokenManager
  - TAB